apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-deployment
  labels:
    app: tawazun
    name: Najwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun-via-dep
  template:
    metadata:
      labels:
        app: tawazun-via-dep
    spec:
      containers:
      - name: tawazun
        image: algow/tawazun:latest
        env:
          - name: DB_URL
            value: mysql
          - name: DB_NAME
            value: tawazun
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: NajwaA
          - name: DB_PORT
            value: "3306"
        ports:
        - containerPort: 8080
